export const FETCH_COURSES_REQUEST = 'FETCH_COURSES_REQUEST';
export const FETCH_COURSES_SUCCESS = 'FETCH_COURSES_SUCCESS';
export const FETCH_COURSES_FAILURE = 'FETCH_COURSES_FAILURE';
export const ADD_NEW_USER = 'ADD_NEW_USER';
export const LOGIN_NEW_USER = 'LOGIN_NEW_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
